#!/usr/bin/env python

# Name: 		Check Project
# Type:         Execute
# Script type:	Shell
# Description:	Verify if project to delete exists
# Script Type:  Shell

import boto, sys, shelve

try:
    db = shelve.open("@@{project_name}@@.db")
except Exception as error:
    print('Unable to open flat file for project @@{project_name}@@: %s' % (error))
    sys.exit(1)

accessID = db["key"]
accessKEY = db["secret"]

try:
    conn = boto.connect_iam(accessID,accessKEY)
except Exception as error:
    print('Connection failed: %s' % (error))
    sys.exit(1)

sys.exit(0)
