#!/usr/bin/env python

# Name:         Deregister AMI
# Type:         Execute
# Script Type:  Shell

# Script:

import boto.ec2, sys, shelve

try:
    db = shelve.open("@@{project_name}@@.db")
except Exception as error:
    print('Failed to open flat file: %s' % (error))
    sys.exit(1)

accessID = db["key"]
accessKEY = db["secret"]
region = db["region"]

#Connect to EC2
try:
    conn = boto.ec2.connect_to_region(region, aws_access_key_id=accessID, aws_secret_access_key=accessKEY)
except Exception as error:
    print('Connection failed: %s' % (error))
    sys.exit(1)

try:
    # Delete image
    conn.deregister_image(db["image_id"], delete_snapshot=True)

except Exception as error:
    print('An error occured while creating the image: %s' % (error))
    sys.exit(1)

try:
    db.sync()
    db.close()
except Exception as error:
    print('Failed to close flat file: %s' % (error))
    sys.exit(1)

sys.exit(0)
