#!/usr/bin/env python

# Type:         Execute
# Script Type:  Shell
# Description:  Delete related keypair

# Script:

import boto.ec2, sys, os, shelve

try:
    db = shelve.open("@@{project_name}@@.db")
except Exception as error:
    print('Unable to open flat file: %s' % (error))
    sys.exit(1)

accessID = db["key"]
accessKEY = db["secret"]
keypair_name=db["project"]+'_keypair'

try:
    conn = boto.ec2.connect_to_region(db["region"], aws_access_key_id=accessID, aws_secret_access_key=accessKEY)
except Exception as error:
    print('Connection failed: %s' % (error))
    sys.exit(1)

try:
    # delete key pair in AWS
    conn.delete_key_pair(keypair_name)
except Exception as error:
    print('Failed to delete key pair in AWS: %s' % error)
    sys.exit(1)

try:
    # delete key pair file
    os.remove(keypair_name+'.pem')
except Exception as error:
    print('Failed to delete key pair file: %s' % error)
    sys.exit(1)

try:
    db.sync()
    db.close()
except Exception as error:
    print('Failed to close flat file: %s' % (error))
    sys.exit(1)

sys.exit(0)
