#!/usr/bin/env python

# Create VPC

# Name:         Delete VPC and dependencies
# Type:         Execute
# Script Type:  Shell
# Description:	Detach the Internet Gateway, delete the subnet, route table, security group, vpc and internet gateway

# Script:

import boto, boto.vpc, sys, shelve

try:
    db = shelve.open("@@{project_name}@@.db")
except Exception as error:
    print('Unable to open flat file: %s' % (error))
    sys.exit(1)

accessID = db["key"]
accessKEY = db["secret"]

try:
	conn = boto.vpc.connect_to_region(db["region"], aws_access_key_id=accessID, aws_secret_access_key=accessKEY)
except Exception as error:
	print('Connection failed: %s' % (error))
	sys.exit(1)




try:
    conn.detach_internet_gateway(db["gateway_id"],db["vpc_id"])
except Exception as error:
	print('Failed to detach internet gateway: %s' % (error))
	sys.exit(1)
try:
    conn.delete_subnet(db["subnet_id"])
except Exception as error:
	print('Failed to delete subnet: %s' % (error))
	sys.exit(1)
try:
    conn.delete_route_table(db["route_table_id"])
except Exception as error:
	print('Failed to delete route table: %s' % (error))
	sys.exit(1)
try:
    conn.delete_security_group(None,db["sg_id"])
except Exception as error:
	print('Failed to delete security group: %s' % (error))
	sys.exit(1)
try:
    conn.delete_vpc(db["vpc_id"])
except Exception as error:
	print('Failed to delete vpc: %s' % (error))
	sys.exit(1)
try:
    conn.delete_internet_gateway(db["gateway_id"])
except Exception as error:
	print('Failed to delete internet gateway: %s' % (error))
	sys.exit(1)
