#!/usr/bin/env python

# Name: 		Delete IAM User and Role
# Type:         Execute
# Script type:	Shell

# Script:
import boto, sys, shelve

try:
    db = shelve.open("@@{project_name}@@.db")
except Exception as error:
    print('Unable to open flat file: %s' % (error))
    sys.exit(1)

accessID = db["key"]
accessKEY = db["secret"]

try:
	conn = boto.connect_iam(accessID,accessKEY)
except Exception as error:
	print('Connection failed: %s' % (error))
	sys.exit(1)

try:
	conn.remove_role_from_instance_profile(db["rolename"], db["rolename"])
	conn.delete_instance_profile(db["rolename"])
	conn.delete_role(db["rolename"])
except Exception as error:
	print('Error in role deletion: %s' % (error))
	sys.exit(1)

try:
    db.sync()
    db.close()
except Exception as error:
    print('Failed to close flat file: %s' % (error))
    sys.exit(1)

sys.exit(0)
