#!/usr/bin/env python

import sys, os, shelve

try:
    for file in os.listdir("."):
        if file.endswith(".db"):
            db = shelve.open(file)
            if len(db) == 0:
                os.remove(file)
            else:
                print(os.path.splitext(file)[0])
except Exception as error:
    print('Error while getting list of projects: %s' % (error))
    sys.exit(1)

sys.exit(0)
