#!/usr/bin/env python

# Name: 		Create IAM Role
# Type:         Execute
# Script type:	Shell
# Description:	Create an IAM role on the AWS account
# Script Type:  Shell
# New keys:		rolename

# Script:
import boto, sys, shelve

try:
    db = shelve.open("@@{project_name}@@.db")
except Exception as error:
    print('Unable to open flat file: %s' % (error))
    sys.exit(1)

accessID = db["key"]
accessKEY = db["secret"]

db["rolename"] = db["project"]+'_role'

try:
	conn = boto.connect_iam(accessID,accessKEY)
except Exception as error:
	print('Connection failed: %s' % (error))
	sys.exit(1)

try:
	role_response = conn.create_role(db["rolename"])
	profile = conn.create_instance_profile(db["rolename"])
	conn.add_role_to_instance_profile(db["rolename"], db["rolename"])
except Exception as error:
	print('Error in role creation: %s' % (error))
	sys.exit(1)

try:
    db.sync()
    db.close()
except Exception as error:
    print('Failed to close flat file: %s' % (error))
    sys.exit(1)

sys.exit(0)
