#!/usr/bin/env python

# Create VPC

# Name:         Create VPC
# Type:         Execute
# Script Type:  Shell
# Description:	Create a new VPC, a gateway, and connect the VPC to the gateway
# New keys:     vpc_id
#               gateway_id

# Script:

import boto, boto.vpc, sys, shelve

try:
    db = shelve.open("@@{project_name}@@.db")
except Exception as error:
    print('Unable to open flat file: %s' % (error))
    sys.exit(1)

accessID = db["key"]
accessKEY = db["secret"]

try:
	conn = boto.vpc.connect_to_region(db["region"], aws_access_key_id=accessID, aws_secret_access_key=accessKEY)
except Exception as error:
	print('Connection failed: %s' % (error))
	sys.exit(1)

try:
	#Create VPC
    vpc = conn.create_vpc(db["cidr"])

    # Configure the VPC to support DNS resolution and hostname assignment
    conn.modify_vpc_attribute(vpc.id, enable_dns_support=True)
    conn.modify_vpc_attribute(vpc.id, enable_dns_hostnames=True)

    # Create an internet gateway
    gateway = conn.create_internet_gateway()

    # Attach the gateway to the VPC
    conn.attach_internet_gateway(gateway.id, vpc.id)

    db["vpc_id"] = vpc.id
    db["gateway_id"] = gateway.id

except Exception as error:
    print('An error occured while creating the VPC: %s' % (error))
    sys.exit(1)

# print('vpc_id = %s' % vpc.id)
# print('gateway_id = %s' % gateway.id)

try:
    db.sync()
    db.close()
except Exception as error:
    print('Failed to close flat file: %s' % (error))
    sys.exit(1)

sys.exit(0)
