#!/usr/bin/env python

# Name:         Validate Network
# Type:         Execute
# Script Type:  Shell
# Description:  Verify is Subnet fits into CIDR
# Script:

import netaddr, sys, shelve

try:
    db = shelve.open("@@{project_name}@@.db")
except Exception as error:
    print('Unable to open flat file: %s' % (error))
    sys.exit(1)



try:
    substat = netaddr.IPNetwork(db["cidr"]).first <= netaddr.IPNetwork(db["subnet"]).last and netaddr.IPNetwork(db["subnet"]).first <= netaddr.IPNetwork(db["cidr"]).last
    if not substat:
        raise Exception('The subnet does not fit into the CIDR')

except Exception as error:
    print('An error occured while validating the subnet: %s' % (error))
    sys.exit(1)

try:
    db.sync()
    db.close()
except Exception as error:
    print('Failed to close flat file: %s' % (error))
    sys.exit(1)

sys.exit(0)
