#!/usr/bin/env python

# Name:         Create keypair
# Type:         Execute
# Script Type:  Shell
# Description:  Generate a keypair, download file and save keys in flat file

# Script:

import boto.ec2, sys, os, shelve

try:
    db = shelve.open("@@{project_name}@@.db")
except Exception as error:
    print('Unable to open flat file: %s' % (error))
    sys.exit(1)

accessID = db["key"]
accessKEY = db["secret"]
keypair_name=db["project"]+'_keypair'

try:
    conn = boto.ec2.connect_to_region(db["region"], aws_access_key_id=accessID, aws_secret_access_key=accessKEY)
except Exception as error:
    print('Connection failed: %s' % (error))
    sys.exit(1)

try:
# Create key pair
    keypair = conn.create_key_pair(keypair_name)

    # Download key pair
    keypair.save('.')
    os.chmod(keypair_name+'.pem', 0400)
except Exception as error:
    print('Keypair creation of download failed: %s' % error)
    sys.exit(1)

# print(os.popen('cat %s.pem\n' % keypair_name).read())
db["private_key"] = os.popen('cat %s.pem\n' % keypair_name).read()
# print(os.popen('ssh-keygen -y -f %s.pem\n' % keypair_name).read())
db["public_key"] = os.popen('ssh-keygen -y -f %s.pem\n' % keypair_name).read()

print ('Your key pair file has been downloaded in %s/%s.pem' % (os.getcwd(), keypair_name))

try:
    db.sync()
    db.close()
except Exception as error:
    print('Failed to close flat file: %s' % (error))
    sys.exit(1)

sys.exit(0)
