#!/usr/bin/env python

# Author:       Akim Sissaoui
# Action:       Create Project
# Name: 		Create flat file
# Type:         Execute
# Script type:  Shell
# Description:  Create a flat file named after the project name Variable
#               and save variables inside
# Script Type:  Shell
# Variable:     project_name
#   regex:      ^[a-zA-Z0-9\_]+$

# Script:

import shelve, sys, re, os.path

# Check if project exist
try:
    if os.path.exists("@@{project_name}@@.db"):
        raise Exception('This project already exist. Please use a unique project name')
except Exception as error:
    print('Error while creating a new project: %s' % (error))
    sys.exit(1)

# Create a flat file table for the project
try:
    db = shelve.open("@@{project_name}@@.db")
    db["project"] = "@@{project_name}@@"
    db["secret"] = "@@{aws_cred.password}@@"
    db["key"] = "@@{aws_cred.username}@@"
    db["region"] = "@@{region}@@"
    db["cidr"] = "@@{cidr}@@"
    db["subnet"] = "@@{subnet}@@"
    db["ami_id"] = "@@{ami_id}@@"
    db["instance_type"] = "@@{instance_type}@@"
    db["tcp_ports"] = "@@{tcp_ports}@@"
    db["udp_ports"] = "@@{udp_ports}@@"
    db["pc_user"] = "@@{pc_cred.username}@@"
    db["pc_password"] = "@@{pc_cred.password}@@"
except Exception as error:
    print('Error while creating flat file: %s' % (error))
    sys.exit(1)

for key in list(db.keys()):
    print(key+": "+db[key])

try:
    db.sync()
    db.close()
except Exception as error:
    print('Failed to save variables to flat file: %s' % (error))
    sys.exit(1)

sys.exit(0)
