#!/usr/bin/env python

# Name:         Update CentOS
# Type:         Execute
# Script Type:  Shell
# Description:  Update CentOS in the AWS Instance

import sys, subprocess, shelve

try:
    db = shelve.open("@@{project_name}@@.db")
except Exception as error:
    print('Failed to open flat file: %s' % (error))
    sys.exit(1)

host = db["public_ddns_name"]
user = 'centos'
login = user+'@'+host
key = db["project"]+'_keypair.pem'

# update OS in instance
print 'yum update'
print '----------'
runyum = subprocess.Popen(["ssh", login, "-o", "UserKnownHostsFile=/dev/null", "-o", "StrictHostKeyChecking=no", "-i", key, "sudo yum update -y"],shell=False,stdout=subprocess.PIPE,bufsize=1,stderr=subprocess.PIPE)
for line in iter(runyum.stdout.readline, b''):
    print line,
runyum.stdout.close()
runyum.wait()
print

try:
    db.sync()
    db.close()
except Exception as error:
    print('Failed to close flat file: %s' % (error))
    sys.exit(1)

sys.exit(0)
