#!/usr/bin/env python

# Name: 		Validate AWS credentials
# Type:         Execute
# Script type:	Shell
# Description:	Get IAM details to validate AWS credentials
# Script Type:  Shell

# Script:
import boto, sys
accessID = "@@{aws_secret_access_key}@@"
accessKEY = "@@{aws_access_key_id}@@"

try:
	conn = boto.connect_iam(accessID,accessKEY)
except Exception as error:
	print('Connection failed: %s' % (error))
	sys.exit(1)

try:
	summary = conn.get_account_summary()
except Exception as error:
	print('Unable to get summary: %s' % (error))
	sys.exit(1)

sys.exit(0)
