#!/usr/bin/env bash

# Author:      Akim Sissaoui
# Service:     admin
# Action:      Create
# Task:        1_Change_root_password
# Type:        Execute
# Script Type: Shell

# Script:

set -ex

echo '@@{rootpassword}@@' | sudo passwd root --stdin
