#!/usr/bin/env bash

# Type:        Execute
# Script Type: Shell

# Script:

set -ex

echo Create ssh group
sudo groupadd @@{sshgroup}@@

echo add new user to ssh group
sudo usermod -aG @@{sshgroup}@@ @@{admin_cred.username}@@

echo Disable ssh root login
sudo sed -i 's/#PermitRootLogin yes/PermitRootLogin no/g' /etc/ssh/sshd_config

echo Disable ssh password authentication
sudo sed -i 's/PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config

echo Allow only members of ssh group to login using ssh
echo 'AllowGroups @@{sshgroup}@@' | sudo tee -a /etc/ssh/sshd_config

sudo service sshd restart
