#!/usr/bin/env python

# Name:         Deregister AMIs
# Type:         Execute
# Script Type:  Shell

# Script:

import boto.ec2, sys, shelve, os

def treat(file):

    accessID = db["key"]
    accessKEY = db["secret"]
    region = db["region"]

    #Connect to EC2
    try:
        conn = boto.ec2.connect_to_region(region, aws_access_key_id=accessID, aws_secret_access_key=accessKEY)
    except Exception as error:
        print('Connection failed: %s' % (error))
        pass

    try:
        # Delete image
        conn.deregister_image(db["image_id"], delete_snapshot=True)

    except Exception as error:
        print('An error occured while creating the image: %s' % (error))
        pass

for file in os.listdir("."):
    try:
        if file.endswith(".db"):
            db = shelve.open(file)
            if len(db) == 0:
                os.remove(file)
            else:
                treat(file)
    except Exception as error:
        print('Error while deregistering AMI for project %s: %s' % (db["project_name"],error))
        pass

sys.exit(0)
