#!/usr/bin/env bash

# Author:      Akim Sissaoui
# Service:     admin
# Action:      Package Install
# Task:        Install
# Type:        Execute
# Script Type: Shell
# Description: Install required packages

# Script:

set -ex

sudo yum update -y
sudo yum install nano htop -y

sudo yum install epel-release python3 -y
sudo yum install python3 wget -y

sudo pip3 install --upgrade pip
sudo pip3 install boto3 netaddr
